### PR TITLE
refactor(orders): add status for cancelled order

### LINKED ISSUE #124: Order statuses
An user should not be able to delete an order from the database. Instead set its status to `CANCELED`

### PR DESCRIPTION
**Pull request by nullndr**
Close #124 

## Changelog

Add `CANCELLED` enumerator in `OrderStatus`.

Refactor `deleteOrders` function.

### CODE REVIEW

**Review by DaruZero — APPROVED** [review]
:ok_hand:

**Review by DaruZero — CHANGES_REQUESTED** [review]
Update documentation

**Comment by nullndr** [comment]
What docs? The function interfaces didn't change

**Comment by DaruZero** [comment]
[Description](https://github.com/Systax-Technologies/backend/blob/main/README.md#deleteapiv1warehouseordersby-id) should say "Sets an order's status to `CANCELED`"

**Review by DaruZero — APPROVED** [review]
:+1:

**Pull request merged**
